compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

plugins:
  - checksum: a3737f25a9d21a5b5a1b4f7432f437b704fdc8a89b7a36356148752da776c0b14b002d9f702230e841efa13f278c6fce4b47b8847623df2527dcf5e86b863f81
    path: .yarn/plugins/@yarnpkg/plugin-npm-ping.cjs
    spec: packages/plugin-npm-ping/bundles/@yarnpkg/plugin-npm-ping.js

preferDeferredVersions: true

yarnPath: .yarn/releases/yarn-4.12.0.cjs
