approvedGitRepositories:
  - "**"

compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

npmMinimalAgeGate: 15d

preferDeferredVersions: true

yarnPath: .yarn/releases/yarn-4.18.0.cjs
